package com.sample
 
import com.sample.Fato;
import com.sample.Paciente;

/*
 * Expert System - What is My Disease? / Sistema Especialista - Qual a minha doenca?
 *
 * students:
 * Lucas cordeiro da silva
 * Gleyson
 * Lucas Mengue
 * Douglas
 */

rule "CORIZA"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.CORIZA) from $fatos)
    then
        $p.addPesoDoencas("PNEUMONIA",20);
        $p.addPesoDoencas("RUBEOLA",10);
        $p.addPesoDoencas("SARAMPO",10);
end

rule "DELIRIO"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.DELIRIO) from $fatos)
    then
        $p.addPesoDoencas("MALARIA",30); 
end

rule "DIFICULDADE_DE_ENGOLIR"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.DIFICULDADE_DE_ENGOLIR) from $fatos)
    then
        $p.addPesoDoencas("AMIGDALITE",20);  
end

rule "AUMENTO_GANGLIOS_LINFATICOS"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.AUMENTO_GANGLIOS_LINFATICOS) from $fatos)
    then
        $p.addPesoDoencas("RUBEOLA",10);
end

rule "AMIGDALAS_INCHADAS_E_VERMELHAS"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.AMIGDALAS_INCHADAS_E_VERMELHAS) from $fatos)
    then
        $p.addPesoDoencas("AMIGDALITE",30);
end

rule "FEBRE"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.FEBRE) from $fatos)
    then
        $p.addPesoDoencas("AMIGDALITE",10);
        $p.addPesoDoencas("DENGUE",20);
        $p.addPesoDoencas("PNEUMONIA",10); 
        $p.addPesoDoencas("MALARIA",10);
        $p.addPesoDoencas("SARAMPO",10);
        $p.addPesoDoencas("RUBEOLA",10);
end

rule "DIFICULDADE_DE_RESPIRAR"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.DIFICULDADE_DE_RESPIRAR) from $fatos)
    then
        $p.addPesoDoencas("PNEUMONIA",30);
end

rule "DOR_DE_CABECA"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.DOR_DE_CABECA) from $fatos)
    then
        $p.addPesoDoencas("RUBEOLA",10);
        $p.addPesoDoencas("MALARIA",20); 
        $p.addPesoDoencas("AMIGDALITE",10);
        $p.addPesoDoencas("DENGUE",10);
end

rule "DOR_DE_GARGANTA"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.DOR_DE_GARGANTA) from $fatos)
    then
        $p.addPesoDoencas("AMIGDALITE",20);
end


rule "DOR_NO_CORPO"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.DOR_NO_CORPO) from $fatos)
    then
        $p.addPesoDoencas("RUBEOLA",20); 
        $p.addPesoDoencas("MALARIA",10);
        $p.addPesoDoencas("PNEUMONIA",10);
end

rule "FOTOFOBIA"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.FOTOFOBIA) from $fatos)
    then
        $p.addPesoDoencas("SARAMPO",10);
end

rule "FRAQUEZA"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.FRAQUEZA) from $fatos)
    then
        $p.addPesoDoencas("PNEUMONIA",10);
        $p.addPesoDoencas("DENGUE",10);
end

rule "IRRITAÇAO_OCULAR"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.IRRITAÇAO_OCULAR) from $fatos)
    then
        $p.addPesoDoencas("SARAMPO",20);
end

rule "MANCHAS_E_ERUPCOES_NA_PELE"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.MANCHAS_E_ERUPCOES_NA_PELE) from $fatos)
    then
        $p.addPesoDoencas("RUBEOLA",20);
        $p.addPesoDoencas("SARAMPO",30);
        $p.addPesoDoencas("DENGUE",20);
end

rule "SONOLENCIA"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.SONOLENCIA) from $fatos)
    then
        $p.addPesoDoencas("MALARIA",20);
end

rule "TOSSE"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.TOSSE) from $fatos)
    then
        $p.addPesoDoencas("SARAMPO",20);
        $p.addPesoDoencas("PNEUMONIA",20);
end

rule "VOMITO"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.VOMITO) from $fatos)
    then
        $p.addPesoDoencas("MALARIA",10);
        $p.addPesoDoencas("DENGUE",10);
end

rule "VOZ_ROUCA"
    when
        $p : Paciente( $fatos : fatos   ) and
        exists (Fato( this == Fato.VOZ_ROUCA) from $fatos)
    then
        $p.addPesoDoencas("AMIGDALITE",10);
end
